# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = ["core.py"]

doc_url = "https://QiwenZz.github.io/public_data_food_analysis_3/"

git_url = "https://github.com/QiwenZz/public_data_food_analysis_3/tree/master/"

def custom_doc_links(name): return None
