# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"universal_key": "00_core.ipynb",
         "find_date": "00_core.ipynb",
         "find_float_time": "00_core.ipynb",
         "week_from_start": "00_core.ipynb",
         "load_public_data": "00_core.ipynb",
         "filtering_usable_data": "00_core.ipynb",
         "prepare_baseline_and_intervention_usable_data": "00_core.ipynb",
         "in_good_logging_day": "00_core.ipynb",
         "most_active_user": "00_core.ipynb",
         "convert_loggings": "00_core.ipynb",
         "get_certain_types": "00_core.ipynb",
         "breakfast_analysis_summary": "00_core.ipynb",
         "breakfast_analysis_variability": "00_core.ipynb",
         "breakfast_avg_histplot": "00_core.ipynb",
         "breakfast_sample_distplot": "00_core.ipynb",
         "dinner_analysis_summary": "00_core.ipynb",
         "dinner_analysis_variability": "00_core.ipynb",
         "dinner_avg_histplot": "00_core.ipynb",
         "dinner_sample_distplot": "00_core.ipynb",
         "swarmplot": "00_core.ipynb",
         "FoodParser": "00_core.ipynb",
         "read_logging_data": "01_columbia.ipynb",
         "get_phase_duration": "01_columbia.ipynb",
         "caloric_entries": "01_columbia.ipynb",
         "mean_daily_eating_duration": "01_columbia.ipynb",
         "std_daily_eating_duration": "01_columbia.ipynb",
         "earliest_entry": "01_columbia.ipynb",
         "find_percentiles": "01_columbia.ipynb",
         "logging_day_counts": "01_columbia.ipynb",
         "find_missing_logging_days": "01_columbia.ipynb",
         "make_table": "01_columbia.ipynb"}

modules = ["core.py",
           "columbia.py"]

doc_url = "https://QiwenZz.github.io/public_data_food_analysis_3/"

git_url = "https://github.com/QiwenZz/public_data_food_analysis_3/tree/master/"

def custom_doc_links(name): return None
