# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/treets/',
                'doc_host': 'https://FleischerResearchLab.github.io',
                'git_url': 'https://github.com/FleischerResearchLab/treets/tree/master/',
                'lib_path': 'treets'},
  'syms': {'treets.core': {}}}
